name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04  # Versão mais estável para builds do Buildozer

    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            autoconf automake libtool libtool-bin pkg-config libffi-dev \
            libssl-dev python3-dev openjdk-17-jdk-headless \
            zip unzip python3-setuptools

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Buildozer and Cython
        run: |
          pip install --user --upgrade "Cython<3.0" buildozer
          echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: |
          export APP_ANDROID_ACCEPT_SDK_LICENSE=1
          # O parâmetro -v mostra o log detalhado caso ocorra erro de compilação
          yes y | python3 -m buildozer -v android debug
        env:
          PATH: /home/runner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ndsn-release
          path: bin/*.apk
